# Generated by Django 5.1.7 on 2025-03-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_opening_reading', models.IntegerField(default=0)),
                ('amount_closing_reading', models.IntegerField(blank=True, null=True)),
                ('dispenser_opening_reading', models.IntegerField(default=0)),
                ('dispenser_closing_reading', models.IntegerField(blank=True, null=True)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.subunit')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('pickup_diesel', 'Pickup Diesel'), ('intra_v30_diesel', 'Intra V30 Diesel'), ('ace_new_diesel', 'ACE New Diesel'), ('diesel', 'Diesel'), ('salary', 'Salary'), ('electricity', 'Electricity'), ('plant_expense', 'Plant Expense'), ('petrol', 'Petrol'), ('nagar_palika', 'Nagar Palika'), ('others', 'Others')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_dashboard.worker')),
            ],
        ),
    ]
