# Generated by Django 5.1.7 on 2025-03-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
