# Generated by Django 5.1.7 on 2025-03-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_reportgeneration'),
        ('manager_dashboard', '0002_alter_attendance_is_present_alter_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeUnitDailyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_reading', models.IntegerField(default=0)),
                ('closing_reading', models.IntegerField(blank=True, null=True)),
                ('recharge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.rechargeunit')),
            ],
        ),
    ]
