# Generated by Django 5.1.7 on 2025-03-23 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_reportgeneration'),
        ('manager_dashboard', '0003_rechargeunitdailyreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOpeningSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount_opening', models.IntegerField(default=0)),
                ('dispenser_opening', models.IntegerField(default=0)),
                ('subunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.subunit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('subunit', 'date')},
            },
        ),
    ]
