# Generated by Django 5.1.7 on 2025-03-23 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_reportgeneration'),
        ('manager_dashboard', '0004_monthlyopeningsub'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeUnitMonthlyOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_reading', models.IntegerField(default=0)),
                ('recharge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.rechargeunit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('recharge_unit', 'date')},
            },
        ),
    ]
