# Generated by Django 5.1.7 on 2025-03-25 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_resethistory'),
        ('manager_dashboard', '0005_rechargeunitmonthlyopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyopeningsub',
            name='reset_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.resethistory'),
        ),
        migrations.AddField(
            model_name='rechargeunitmonthlyopening',
            name='reset_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.resethistory'),
        ),
    ]
