# Generated by Django 5.1.7 on 2025-03-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_customuser_is_deleted_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_units', to='admin_dashboard.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
