# Generated by Django 5.1.7 on 2025-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_reportgeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('subunit_reset', 'Subunit Reset'), ('recharge_fill', 'Recharge Fill')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('is_undo', models.BooleanField(default=False)),
            ],
        ),
    ]
