# Generated by Django 5.1.7 on 2025-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_resethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resethistory',
            name='action_type',
            field=models.CharField(choices=[('subunit_reset', 'Subunit Reset'), ('recharge_fill', 'Recharge Fill'), ('subunit_reset_plus', 'Subunit Reset+'), ('recharge_fill_plus', 'Recharge Fill+')], max_length=20),
        ),
    ]
